name: Create Tag and Update File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-tag-and-update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update test.txt
      run: |
        echo "Random text - Run Number: ${{ github.run_id }}" >> test.txt
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add test.txt
        git commit -m "Update test.txt with run number"

    - name: Create and Push Tag
      run: |
        TAG_NAME="v${GITHUB_RUN_ID}"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
